language: android
android:
  components:
    # use the latest tools Travis will allow
    - tools # needs to be first to get new package versions
    - build-tools-25.0.2
    - platform-tools
    - android-25
    - android-22

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-25
    - sys-img-armeabi-v7a-android-12
env:
  # API level will be determined by the AVD that is created and run
  - _FORCE_LOGS=1 TEST=unit AVD_TARGET=android-21 ABI=armeabi-v7a
  - _FORCE_LOGS=1 TEST=functional AVD_TARGET=android-21 ABI=armeabi-v7a
  - _FORCE_LOGS=1 TEST=functional AVD_TARGET=android-22 ABI=armeabi-v7a
before_script:
  # node stuff
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh | bash
  - nvm install 6
  - npm install -g gulp
  - npm install -g mocha
  - npm install

  # android stuff, as long as there is an AVD specification
  - android list targets
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
script:
  - gulp eslint && DEVICE=android mocha -t 900000 -R spec build/test/$TEST
after_success:
  - gulp coveralls
